---
title: "Market Basket Analysis"
output: html_notebook
---


```{r}
market_basket <- read.transactions(
  file = '../data/market_basket.csv',
  sep = ',', 
  quote = "",
  format = 'basket', # each record in the file will be treated as transaction
  rm.duplicates = TRUE,
  skip=1
)
```


```{r}
# inspecting first 5 transactions
market_basket %>% head(n=5) %>% inspect
```

```{r}
# plot for 10 most frequently brought items
itemFrequencyPlot(x = market_basket,
                  topN = 10,
                  type = 'absolute',
                  horiz = TRUE,
                  col = brewer.pal(10,'Spectral'))
```


```{r}
rule1 <- market_basket %>% apriori(parameter = list(supp = 0.005, conf=0.8)) %>% sort(by = 'confidence')
```

```{r}
summary(rule1)
```

```{r}
rule1 %>% head(n=5)%>% inspect
```

```{r}
rule1 %>% tail(n=5)%>% inspect
```
```{r}
rule1 <- rule1 %>% sort(by='lift')
rule1 %>% head(n=5)%>% inspect
```

```{r}
plot(rule1, engine='htmlwidget')
```

```{r}
plot(rule1, method='two-key', engine='htmlwidget')
```

```{r}
plot(rule1, method='graph', engine='htmlwidget')
```

